owner: openpotato
repo: uptime

sites:
  - name: OpenHolidays API
    url: https://openholidaysapi.org/Countries
    method: GET
    headers:
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 200
  - name: OpenHolidays API Website
    url: https://www.openholidaysapi.org/de

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: OpenPotato Uptime
  introTitle: "**OpenPotato** Uptime"
  introMessage: This status page monitors all OpenPotato projects for uptime.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
