owner: openpotato
repo: uptime

sites:
  - name: OpenHolidays API
    url: https://openholidaysapi.org/Countries
    icon: https://openholidaysapi.org/swagger/favicon-32x32.png
    method: GET
    headers:
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 200
  - name: OpenHolidays API Website
    url: https://www.openholidaysapi.org/de
    icon: https://www.openholidaysapi.org/de/assets/logos/favicon.ico
  - name: OpenPLZ API
    url: https://openplzapi.org/de/FederalStates
    icon: https://openplzapi.org/swagger/favicon-32x32.png
    method: GET
    headers:
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 200
  - name: OpenPLZ API Website
    url: https://www.openplzapi.org/de
    icon: https://www.openplzapi.org/de/assets/logos/favicon.ico

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/openpotato/uptime/master/assets/openpotato-icon.svg
  name: OpenPotato Uptime
  introTitle: "**OpenPotato** Uptime"
  introMessage: This status page monitors all OpenPotato projects for uptime.
  faviconSvg: https://raw.githubusercontent.com/openpotato/uptime/master/assets/openpotato-icon.svg
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"      


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
